# fly.toml app configuration file generated for simonhartcher-com on 2023-04-21T10:45:54+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simonhartcher-com"
primary_region = "syd"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false

[[http_service.checks]]
  interval = "60s"
  timeout = "5s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[build.args]
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID="G-M5R396MEP8"
  NEXT_PUBLIC_POSTHOG_ID="phc_gzmQetR04l175u1OwF6SEb0kLGQusXUIBGjTTcSyV2j"

[mounts]
  source="simonhartcher_com_image_cache"
  destination="/app/.next/cache"
