name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    services:
      image: redis

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --frozen-lockfile
      - name: build
        env:
          NEXT_PUBLIC_GTM_CONTAINER_ID: G-V93V2LBLYK
          REDIS_HOST: redis
          REDIS_PASSWORD:
        run: yarn build
